---

#- import_tasks: "tasks/service/pcm/pkg/astra linux_1.yml"

- name: "pcm packages list"
  ansible.builtin.package_facts:
    manager: auto

- name: "pcm install from github for astra linux"
  become: true
  ansible.builtin.apt:
    deb: https://github.com/pnsafonov/pcm_pkg/releases/download/202405/pcm-202405.deb
    state: present
  when: >
    'pcm' not in ansible_facts.packages
